### PR TITLE
Fix textdomain loading and remove hashtags

### PR DESCRIPTION
**Pull request by maurobringolf**
I wanted to convert to WP Coding standards and found that the loading of the textdomain was not quite right. Please correct me if I am wrong, I have not tested it with actual translation files. Plus in order to run the plugin I had to remove the hashtags from the placeholders.

### CODE REVIEW

**Comment by markhowellsmead** [comment]
Switching to WP coding standards might be problematic for developers who adhere to the wider PSR coding standards. e.g. spaces vs. tabs. Also, the hashes should be replaced with double underscores, as per our discussion last week. Note that this plugin isn't designed to be used or installed in WordPress without first converting it.

**Comment by markhowellsmead** [comment]
(PSR not OSR.)

**Comment by maurobringolf** [comment]
Okay, my comment above might be misleading. The purpose of this PR are the changes I made to the load text domain function, because I think it will not work the way it is right now. As far as I can see, the method name within the ```add_action``` call is wrong as well as the directory specified for languages (unless you want to load languages from ```Classes/languages```). Again, correct me if I am wrong here.

**Comment by markhowellsmead** [comment]
The `dirname` part of the code (as it was) has always worked for me in the past. Although the entire `load_text_domain` process can be removed entirely anyway, as translations are [loaded automatically](https://make.wordpress.org/core/2016/07/06/i18n-improvements-in-4-6/) from 4.6 onwards and `wp_compare_version` demands 4.6.

**Pull request merged**
